# Generated by Django 4.1.1 on 2022-09-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('id_medico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='signos_vitales',
            fields=[
                ('id_signo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor_maximo', models.IntegerField()),
                ('valor_minimo', models.IntegerField()),
                ('recomendacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='historias_signos',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('valor_signo', models.IntegerField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_paciente', to='hospi_casa_app.pacientes')),
                ('id_signo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_signo_vitales', to='hospi_casa_app.signos_vitales')),
            ],
        ),
        migrations.CreateModel(
            name='historias_clinicas',
            fields=[
                ('id_historia_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=200)),
                ('recomendaciones', models.IntegerField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_medico', to='hospi_casa_app.medicos')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_pacientes', to='hospi_casa_app.pacientes')),
            ],
        ),
    ]
