# Generated by Django 4.1.1 on 2022-09-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospi_casa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historias_clinicas',
            name='recomendaciones',
            field=models.CharField(max_length=200),
        ),
    ]
